version: 2.0

jobs:
  release:
    docker:
      - image: circleci/python:2.7-stretch
    working_directory: /tmp
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            docker pull gliderlabs/herokuish:latest
            docker run --name plotly-herokuish gliderlabs/herokuish:latest /bin/herokuish buildpack install https://github.com/plotly/heroku-buildpack-python $CIRCLE_SHA1 04_buildpack-python
            ID=$(docker inspect plotly-herokuish --format '{{ .ID }}' )
            docker commit $ID quay.io/plotly/herokuish:${CIRCLE_TAG}
      - run:
          name: push the docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
            docker push quay.io/plotly/herokuish:${CIRCLE_TAG}

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
